created new derived guis and dialogues that will go into b26toolkit. However, this now gives an error "AttributeError: 'LoadDialogB26' object has no attribute 'txt_info'", when creating a script. Looked like one can not access the elements on the GUI, which is strange because they should have been inherited from the superclass